# Generated by Django 4.2.5 on 2024-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cost_center",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="cost center"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cost_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="cost type"
            ),
        ),
    ]
