# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import regex.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20151020_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, storage=regex.utils.storages.PrivateMediaFileSystemStorage(), upload_to='invoices/%Y/%m', verbose_name='pdf'),
        ),
    ]
