language: python
python:
  - "3.5"

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.pip-cache

services:
  - postgresql

install:
  - pip install pip --upgrade
  - pip install -r requirements/travis.txt --cache-dir $HOME/.pip-cache

before_script:
  - mkdir log
  - export DJANGO_SETTINGS_MODULE=regex.conf.settings.test
  - npm install bower grunt-cli -g
  - npm install
  - bower install
  - src/manage.py collectstatic --noinput --link
  - grunt sass:dist

script:
  - coverage run src/manage.py test src -v 2

after_success:
  - codecov
  - coveralls
