version: '3.8'

services:
  primary:
    image: docker.io/library/mariadb:10.9-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret
      - MARIADB_DATABASE=test
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
    volumes:
      - primary:/var/lib/mysql
      - ./docker/mariadb/config/primary/:/etc/mysql/conf.d/
      - ./docker/mariadb/primary/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306

  replica:
    image: docker.io/library/mariadb:10.9-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=supersecret
    volumes:
      - replica:/var/lib/mysql
      - ./docker/mariadb/config/replica/:/etc/mysql/conf.d/
      - ./docker/mariadb/replica/:/docker-entrypoint-initdb.d/
    ports:
      - 3308:3306
    depends_on:
      - primary

volumes:
  primary:
  replica:
