---

zabbix_db_host: localhost
zabbix_db_user: zabbix
zabbix_db_password: ''
zabbix_db_name: zabbix

zabbix_server_version: ubuntu-4.4.7
zabbix_server_image: zabbix/zabbix-server-pgsql:{{ zabbix_server_version }}

zabbix_web_version: ubuntu-4.4-latest
zabbix_web_image: zabbix/zabbix-web-nginx-pgsql:{{ zabbix_web_version }}
