# Generated by Django 3.2.16 on 2022-10-16 18:21

import django.db.models.deletion
from django.db import migrations, models

import privates.fields
import privates.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "creditor",
                "verbose_name_plural": "creditors",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=50, verbose_name="identifier"),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Invoice (creation) date", verbose_name="date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="amount"
                    ),
                ),
                (
                    "pdf",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="expenses/invoices/%Y/%m",
                        verbose_name="pdf",
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.creditor",
                        verbose_name="creditor",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
    ]
