# Generated by Django 4.2.5 on 2023-10-08 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_set_file_hashes"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensesconfiguration",
            name="kpn_creditor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="expenses.creditor",
                verbose_name="KPN creditor",
            ),
        ),
    ]
