# Generated by Django 3.2.16 on 2022-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deductions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notes"),
            preserve_default=False,
        ),
    ]
