# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20151102_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('nl_BE', 'Dutch (Belgium)')], default='nl', max_length=10, verbose_name='language'),
        ),
    ]
