---
# perform all SSL related tasks

- name: Load ssl private keys
  include_vars: vars/ssl.yml
  no_log: true

- name: Send private ssl keys
  copy:
    content: "{{ ssl_private_key }}"
    dest: "/etc/ssl/private/wildcard.regex.key"
    mode: 0640
  no_log: true

- name: Copy ssl keys and certs
  copy:
    src: "wildcard.regex.crt"
    dest: "/etc/ssl/certs/regex.crt"

- name: Check if custom DH cert exists
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: has_custom_dh_cert

- name: Generate custom DH cert
  shell: openssl dhparam -out dhparam.pem 4096
         chdir=/etc/ssl/certs/
  when:
    - has_custom_dh_cert.stat.exists == False
