---

- name: Deploy backup server
  hosts: backup
  remote_user: root

  vars:
    firewall_open_ports:
      - '25565'
    postgresql_enabled: false
    nginx_enabled: false
    redis_enabled: false
    nodejs_enabled: false

    application_user: minecraft

  roles:
    - base
    - app_user
