---

- name: Provision the server with all required packages and user accounts
  hosts: "{{ target|default('staging') }}"
  remote_user: root
  vars:
    bigstore: no
    postgresql_enabled: yes
    apache_enabled: no
    nginx_enabled: yes
    redis_enabled: yes
    memcached_enabled: no
    nodejs_enabled: yes
    django_enabled: yes
  roles:
    - base
    - app_user
    - postgres
    - ssl
    - nginx
