collections:
  - name: git@github.com:maykinmedia/commonground-ansible.git
    type: git
    version: main

roles:
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: geerlingguy.postgresql
  - name: nginxinc.nginx
  - name: geerlingguy.certbot
