---

admin_email: root@localhost

# firewall
firewall_open_ports:
  - http
  - https

# big storage (Tansip)
bigstorage: no
bigstorage_device: /dev/vdb1
bigstorage_mount_path: /mnt/bigstorage

# databases
postgresql_enabled: yes
postgresql_version: 10
postgresql_packages:
  - postgresql
  - postgresql-client
  # python bindings
  - python-dev
  - libpq-dev
  - python-psycopg2

# webservers
nginx_enabled: yes
