# Generated by Django 2.2.12 on 2020-04-25 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="company name"),
                ),
                (
                    "company_address",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                        verbose_name="company address",
                    ),
                ),
                (
                    "tax_identifier",
                    models.CharField(max_length=50, verbose_name="tax identifier"),
                ),
                (
                    "coc",
                    models.CharField(
                        max_length=100, verbose_name="chamber of commerce number"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        max_length=100, verbose_name="bank account number"
                    ),
                ),
            ],
            options={
                "verbose_name": "company config",
            },
        ),
    ]
