---

- name: Set up PGSQL backed frontend
  docker_container:
    name: zabbix-web
    image: "{{ zabbix_web_image }}"
    pull: yes
    hostname: zabbix-web
    state: started
    restart: no
    restart_policy: always
    stop_timeout: 30

    purge_networks: yes
    networks_cli_compatible: yes
    networks:
      - name: zabbix

    volumes:
      - /etc/localtime:/etc/localtime:ro

    env:
      DB_SERVER_HOST: "{{ zabbix_db_host }}"
      POSTGRES_DB: "{{ zabbix_db_name }}"
      POSTGRES_USER: "{{ zabbix_db_user }}"
      POSTGRES_PASSWORD: "{{ zabbix_db_password }}"

      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Amsterdam"

    labels:
     com.zabbix.description: "Zabbix frontend"
     com.zabbix.company: "Zabbix LLC"
     com.zabbix.component: "zabbix-frontend"
     com.zabbix.webserver: "nginx"
     com.zabbix.dbtype: "pgsql"
     com.zabbix.os: "ubuntu"

    published_ports:
      - "9000:80"
