---

- name: Set up PGSQL backed server container
  docker_container:
    name: zabbix-server
    image: "{{ zabbix_server_image }}"
    pull: yes
    hostname: zabbix-server
    state: started
    restart: no
    restart_policy: always
    stop_timeout: 30
    networks:
      - name: zabbix

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/postgresql:/var/run/postgresql

    env:
      DB_SERVER_HOST: /var/run/postgresql
      POSTGRES_DB: zabbix
      POSTGRES_USER: "{{ zabbix_db_user }}"
      POSTGRES_PASSWORD: "{{ zabbix_db_password }}"

      ZBX_JAVAGATEWAY_ENABLE: "false"
      ZBX_ENABLE_SNMP_TRAPS: "false"

    ulimits:
     - nproc:65535:65535
     - nofile:20000:40000
    sysctls:
      net.ipv4.ip_local_port_range: '1024 65000'
      net.ipv4.conf.all.accept_redirects: '0'
      net.ipv4.conf.all.secure_redirects: '0'
      net.ipv4.conf.all.send_redirects: '0'
    labels:
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "ubuntu"

    published_ports:
      - "127.0.0.1:10051:10051"
