---

- name: make sure the log dir exists
  file:
    path: "/var/log/nginx/{{ nginx_prefix }}"
    state: directory

- name: Create the nginx vhost
  template:
    src: "{{ nginx_vhost_template }}"
    dest: /etc/nginx/sites-available/{{ nginx_prefix }}.conf
    mode: 0644
  notify: reload nginx

- name: Enable the virtual host
  file:
    src: /etc/nginx/sites-available/{{ nginx_prefix }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_prefix }}.conf
    state: link
  notify: reload nginx
