# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
    ]
