---

- name: Install nginx
  package:
    name: nginx
    state: present
  when: nginx_enabled

- name: Set main config files
  copy:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - nginx.conf
    - conf.d/client_body.conf
    - conf.d/proxy.conf
  notify:
    - restart nginx
  when: nginx_enabled
